#! /bin/csh -f

# cahange to working direcotry with programas and files full or local path
foreach s (`cat /app/cc/amatrice/allstas`)

echo $s
#cd /data/hy73/kw2988/LCSN/cuts
# Waveform cut directory change to full path or local path
cd  /app/cc/cuts
cd $s

#mv ids ids.2019
#mv mseedfiles mseedfiles.2019
#mv newfiles newfiles.2019
#mv newids newids.2019

# cahange to working direcotry with programas and files full or local path
foreach cha (`cat /app/cc/amatrice/chas`)

ls | grep '^[0-9]' | grep -v hdr | grep $cha > mseedfiles.$cha
#grep EHZ mseedfiles > tmp
#mv tmp mseedfiles
awk 'BEGIN{FS="."}{print $1}' mseedfiles.$cha > ids.$cha

end

end
